"""Kestra Flow → dev shell 链（iisp tool invoke 串行）。"""
from __future__ import annotations

import re
from typing import Any

from orchestration.kestra_graph import parse_tool_id_from_uri
from orchestration.loader import discover_kestra_flows, load_pipeline_yaml

_INPUTS_REF = re.compile(r'\binputs\.(\w+)\b')
_OUTPUTS_REF = re.compile(
    r'fromJson\(outputs\.(\w+)\.body\)(?:\.outputs\.(\w+)|)',
)
_PARAM_LITERAL = re.compile(r'"(\w+)":\s*"([^"]+)"')
_PARAM_INPUT = re.compile(r'"(\w+)":\s*inputs\.(\w+)')
_PARAM_OUTPUT = re.compile(
    r'"(\w+)":\s*fromJson\(outputs\.(\w+)\.body\)\.outputs\.(\w+)',
)


def _find_kestra_flow_path(flow_id: str) -> tuple[dict, str]:
    fid = str(flow_id or '').strip()
    for meta in discover_kestra_flows():
        if str(meta.get('id') or '') == fid:
            path = meta.get('_path')
            if path:
                return load_pipeline_yaml(path), path
    raise FileNotFoundError(f'Kestra Flow 未找到: {flow_id}')


def _walk_http_tasks(tasks: list | None, out: list[dict]) -> None:
    for task in tasks or []:
        if not isinstance(task, dict):
            continue
        ttype = str(task.get('type') or '')
        if 'http.Request' in ttype:
            tool_id = parse_tool_id_from_uri(task.get('uri'))
            if tool_id:
                out.append({
                    'id': str(task.get('id') or tool_id),
                    'tool_id': tool_id,
                    'body': str(task.get('body') or ''),
                    'description': task.get('description'),
                })
        for key in ('tasks', 'then', 'else', 'finally', 'errors'):
            _walk_http_tasks(task.get(key), out)
        cases = task.get('cases')
        if isinstance(cases, dict):
            for case_tasks in cases.values():
                _walk_http_tasks(case_tasks, out)


def _flow_input_vars(flow: dict) -> list[dict[str, Any]]:
    rows = []
    for item in flow.get('inputs') or []:
        if not isinstance(item, dict):
            continue
        iid = str(item.get('id') or '').strip()
        if not iid:
            continue
        default = item.get('defaults')
        rows.append({
            'id': iid,
            'default': default,
            'required': bool(item.get('required')),
        })
    return rows


def _body_param_flags(step_id: str, body: str, *, input_vars: set[str]) -> list[str]:
    flags: list[str] = []
    seen: set[str] = set()

    for match in _PARAM_LITERAL.finditer(body):
        key, val = match.group(1), match.group(2)
        if key in seen or key in ('run_id', 'step_id'):
            continue
        if 'outputs.' in val or 'inputs.' in val or 'execution.' in val:
            continue
        seen.add(key)
        flags.append(f'  --param {key}={val}')

    for match in _PARAM_INPUT.finditer(body):
        key, inp = match.group(1), match.group(2)
        if key in seen:
            continue
        seen.add(key)
        var = f'${inp}' if inp in input_vars else f'"${inp}"'
        flags.append(f'  --param {key}="{var}"')

    for match in _PARAM_OUTPUT.finditer(body):
        key, src_step, out_key = match.group(1), match.group(2), match.group(3)
        if key in seen:
            continue
        seen.add(key)
        src_var = f'{src_step}_out'
        flags.append(
            f'  --param {key}="$(jq -r \'.outputs.{out_key}\' <<<"${src_var}")"'
        )

    if not flags and _INPUTS_REF.search(body):
        flags.append('  # 含 inputs 表达式，请按 Flow 注释手调 --param')

    if not flags:
        flags.append('  # 未解析到静态 params，请参照 YAML body 手填 --param')

    return flags


def export_kestra_flow_shell(
    flow_id: str,
    *,
    run_id_var: str = 'RUN_ID',
    iisp_bin: str = './scripts/iisp',
) -> str:
    flow, path = _find_kestra_flow_path(flow_id)
    http_steps: list[dict] = []
    _walk_http_tasks(flow.get('tasks'), http_steps)

    input_rows = _flow_input_vars(flow)
    input_ids = {r['id'] for r in input_rows}

    lines: list[str] = [
        '#!/usr/bin/env bash',
        '# Generated by: iisp flow export-shell',
        f'# Flow: {flow.get("id") or flow_id}',
        f'# Source: {path}',
        '# Dev-only：等价于逐步 iisp tool invoke，不含 Kestra 重试/分支/Pause。',
        'set -euo pipefail',
        'ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"',
        f'IISP="${{IISP:-$ROOT/scripts/iisp}}"',
        f'{run_id_var}="${{{run_id_var}:-cli-$(date +%s)}}"',
        '',
    ]

    if input_rows:
        lines.append('# Flow inputs（可用环境变量覆盖）')
        for row in input_rows:
            iid = row['id']
            default = row['default']
            if default is None:
                lines.append(f': "${{{iid}?"请设置 {iid}"}}"')
            elif isinstance(default, (dict, list)):
                import json
                encoded = json.dumps(default, ensure_ascii=False)
                lines.append(f'{iid}="${{{iid}:-{encoded}}}"')
            else:
                lines.append(f'{iid}="${{{iid}:-{default}}}"')
        lines.append('')

    if not http_steps:
        lines.append('echo "未找到 HTTP 工具步骤" >&2')
        lines.append('exit 1')
        return '\n'.join(lines) + '\n'

    for step in http_steps:
        sid = step['id']
        tool_id = step['tool_id']
        out_var = f'{sid}_out'
        desc = step.get('description')
        lines.append(f'# [{sid}] {tool_id}')
        if desc:
            lines.append(f'# {desc}')
        param_lines = _body_param_flags(sid, step['body'], input_vars=input_ids)
        lines.append(f'{out_var}=$("$IISP" tool invoke {tool_id} \\')
        lines.append(f'  --run-id "${run_id_var}" --step-id {sid} \\')
        for i, pl in enumerate(param_lines):
            suffix = ' \\' if i < len(param_lines) - 1 else ''
            lines.append(f'{pl}{suffix}')
        lines.append(')')
        lines.append(f'echo "[{sid}] $(jq -r \'.status // "?"\' <<<"${out_var}")"')
        lines.append('')

    lines.append('echo "Shell 链执行完毕"')
    return '\n'.join(lines) + '\n'
